### ISSUE TITLE
security content policy error while creating websocket

### ISSUE THREAD

**Issue by guilhebl** [playframework/play-scala-websocket-example#72]
Running with latest version 2.6.x.
Browser is refusing to create websocket based on given URL

Browsers:

Chrome : Version 59.0.3071.109
Firefox: 47.0

ERROR in console:

> Content Security Policy: The page's settings blocked the loading of a resource at ws://localhost:9000/ws 

**Fix provided:** 

https://github.com/playframework/play-scala-websocket-example/pull/71

**Comment by DPGrev** [comment]
Add the following line to the `/conf/application.conf`file:

`play.filters.headers.contentSecurityPolicy = "default-src 'self'; connect-src 'self' ws://localhost:9000/ws;"`

It should then work.
