### ISSUE TITLE
Test web sockets with FakeRequest?

### ISSUE THREAD

**Issue by fancywriter** [playframework/play-scala-websocket-example#75]
I can write unit tests for play controllers if I mix in suite class with **FakeApplicationFactory** and **BaseOneAppPerTest**, providing correct `fakeApplication` method which returns fake application. I can test my controllers with `FakeRequest` object, with GET/POST or other HTTP methods. However, how I can I test web sockets?

**Comment by wsargent** [comment]
https://github.com/playframework/play-scala-websocket-example/blob/2.6.x/test/controllers/FunctionalSpec.scala
